hostname: rancher.javierum.com
ingress:
  enabled: true
  tls:
    source: secret
    secretName: tls-rancher-secret
privateCA: true
replicas: 1
bootstrapPassword: "r4nch3r"
global:
  cattle:
    psp:
    enabled: false
