apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: issuers-certmanager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TFE-javier-urones-devops/base-charts-rancher.git
    targetRevision: main
    path: charts/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: certmanager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true