apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-rancher
  namespace: cattle-system
spec:
  secretName: tls-rancher
  dnsNames:
  - rancher.javierum.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
